# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20191011_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='imagepath/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.CASCADE, to='pictures.Category'),
        ),
    ]
